# Site settings
title: Hi, my name is Ben
description: 'Software Engineer, Musician, Husband, Lover of Puzzles'
url: 'http://benwells.github.io'
baseurl: '/'


# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Ben Wells'
  email: mrbrwells@gmail.com
  twitter_username: mrbrwells
  github_username:  benwells
  linkedin_username:  mrbenwells

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
